language: r
sudo: false
cache: packages

r_github_packages:
   - rstudio/rmarkdown
   
install:
   - R -e "install.packages('devtools')"
   - R -e "devtools::install_github('rstudio/rmarkdown')"
   - R -e 'install.packages(c("knitr", "boot"))'

script:
   - R -e "rmarkdown::render_site()"
   - tools/pdf_all
   - tools/headers

after_success:
   - ./tools/deploy.sh